# hyprpaper.conf
# Add your wallpaper path below. Example uses a solid Catppuccin Base colour
# wallpaper; replace with your own image.

preload = ~/.config/hypr/wallpaper.png
wallpaper = ,~/.config/hypr/wallpaper.png

# Prevent hyprpaper from showing the splash
splash = false
